params:
    ### step1 assembly
    fastp:
      min_len : 70 # Recommended value >= 30
    #rmhost
    rmhost:
      bowtie2_index : "/ldfssz1/ST_META/share/User/tianliu/database/bowtie2_index/hg38/hg38"
      threads: 8
    #megahit
    megahit:
      threads: 8
      min_contigs_len: 200
    #binning
    metabat2:
      multi_samples: 10 # test data : 2, Recommended 10
      threads: 4
      minContig: 1500 #should be >=1500
    #quality
    checkm:
      threads: 8
    pick:
      # "completeness, contamination, strain_heterogeneity" from CheckM
      # Default : MIMAG standard.
      # <0 : no filter
      HQ: "90,5,-1"
      MQ: "50,10,-1"

assay:
    all: "1.assay"
    trimming: "1.assay/01.trimming"
    rmhost: "1.assay/02.rmhost"
    megahit: "1.assay/03.assembly/megahit"
    metabat2: "1.assay/04.binning/metabat2"
    checkm: "1.assay/05.quality/checkm"
    picked: "1.assay/05.quality/picked"

results:
    assembly: "2.result/01.assembly"
    binning_s1: "2.result/02.binning_s1"

logs:
    all: "1.assay/logs"
    trimming: "1.assay/logs/01.trimming"
    rmhost: "1.assay/logs/02.rmhost"
    megahit: "1.assay/logs/03.assembly/megahit"
    metabat2: "1.assay/logs/04.binning/metabat2"
    checkm: "1.assay/logs/05.MAG_quality/checkm"
